version: '3'

services:
  sovereign:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    image: democracy-earth:latest
    ports:
      - 3000:3000
    volumes:
      - ../:/app
      - meteor-data:/home/meteor/
    environment:
      MONGO_URL: "mongodb://mongo:27017"
    depends_on:
      - mongo

  mongo:
    image: mongo
    expose:
      - 27017

volumes:
  meteor-data:
